import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { RiHome7Fill } from 'react-icons/ri'
import { BiSolidBookContent } from 'react-icons/bi'
import { FaDisplay } from 'react-icons/fa6'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Link href='/'>
            <RiHome7Fill size={'2rem'} />
          </Link>
          <Link href='/blog'>
            <BiSolidBookContent size={'2rem'} />
          </Link>
          <Link href='/projects'>
            <FaDisplay size={'1.8rem'} />
          </Link>
        </header>
        {children}
      </body>
    </html>
  )
}
