import './globals.scss'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { RiHome7Fill } from 'react-icons/ri'
import { BiSolidBookContent } from 'react-icons/bi'
import { FaDisplay } from 'react-icons/fa6'
import Image from 'next/image'
import Link from 'next/link'

export const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <header>
          <Image src='/logo.svg' width={47} height={42} alt='Felipe Benini Logo'/>
        </header>
        <nav>
          <Link href='/' aria-label='home'>
            <RiHome7Fill size={'2rem'} aria-label='icon of a house' />
          </Link>
          <Link href='/blog' aria-label='blog'>
            <BiSolidBookContent size={'2rem'} aria-label='icon of a content screen for the blog' />
          </Link>
          <Link href='/projects' aria-label='projects'>
            <FaDisplay aria-label='display icon for projects' size={'1.8rem'} />
          </Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
